server:
  servlet:
    context-path: /cliente-pet/api

spring:
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:demodb
    username: admin
    password: ''


  h2:
    console:
      enabled: true
      path: /h2-console